#!/usr/bin/env bash

shopt -s globstar

# check pre-reqs
apps=(zola)

for app in "${apps[@]}"; do
  if ! command -v $app > /dev/null; then
    echo "error: need install $app" >&2
    exit 1
  fi
done

# push to git
if [[ "$*"  ]]; then
  msg="$*"
else
  while true; do
    read -p 'Push msg: ' msg
    [[ "$msg"  ]] && break
  done
fi

# zola build
zola build
git add -A
git commit -m "${msg^}"
git push
exit 0
