#!/usr/bin/env bash

shopt -s globstar

# check pre-reqs
apps=(esbuild minify zola)

for app in "${apps[@]}"; do
  if ! command -v $app > /dev/null; then
    echo "error: need install $app" >&2
    exit 1
  fi
done

# push to git
if [[ "$*"  ]]; then
  msg="$*"
else
  while true; do
    read -p 'Push msg: ' msg
    [[ "$msg"  ]] && break
  done
fi

# zola build
zola build

# public dir
public="$(pwd)/public"

# bundle and minify css
esbuild "$public/main.css" \
  --bundle \
  --minify \
  --allow-overwrite \
  --loader:.woff2=copy \
  --outfile="$public/css/main.css"

# minify html
for file in "$public"/**/*.html; do
  minify "$file" -o "$file"
done

git add -A
git commit -m "${msg^}"
git push

exit 0
